default:
  outputs:
    dev:
      account: kna33024
      database: bill_dbt_training
      user: bill.raper@g2o.com
      authenticator: externalbrowser
      role: dbt_dev
      schema: dbt_braper
      threads: 1
      type: snowflake
      warehouse: transforming
  target: dev